services:
  postgres:
    image: 'postgres:16'
    container_name: cerclebleu-postgres
    environment:
      POSTGRES_DB: cerclebleu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cerclebleu"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cerclebleu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cerclebleu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
     postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: